config/routes.rb
ChefRef::Application.routes.draw do
  
  get "pasta_rices/index"
  get "pasta_rices/show"
  get "pasta_sides/show"
  get "pasta_sides/index"
  get "sides/show"
  get "sides/index"
  get "meats/show"
  get "meats/index"
  get "categories/show"
  get "categories/index"
  resources :users, :recipes, :meats, :pasta_rices, :sides

  get '/signup' => 'users#new'

  delete '/signout', to: 'sessions#destroy'

  get '/signin' => 'sessions#new'

  root to: 'sessions#new'
  
  resources :sessions

end

app/models/meat.rb
# == Schema Information
#
# Table name: meats
#
#  id            :integer          not null, primary key
#  time          :string(255)
#  cut           :string(255)
#  size          :string(255)
#  temp          :string(255)
#  internal_temp :string(255)
#  rest          :string(255)
#  created_at    :datetime
#  updated_at    :datetime
#

class Meat < ActiveRecord::Base

#           @side.each do |side|    
#            side["Name"]  
# 	     end  

# <div class="btn-group">
#   <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
#     Beef <span class="caret"></span>
#   </button>
#   <ul class="dropdown-menu" role="menu">
#     <% @meat.each do |x| %>
#       <li><a href="meat_path(x)"><%= x.cut %></a></li>
#       <% end %>
#   </ul>
# </div>

end

app/models/pasta_rice.rb
# == Schema Information
#
# Table name: pasta_rices
#
#  id           :integer          not null, primary key
#  type         :string(255)
#  amount       :string(255)
#  amount_water :string(255)
#  time         :string(255)
#  created_at   :datetime
#  updated_at   :datetime
#  rest         :string(255)
#

class PastaRice < ActiveRecord::Base
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :user
end

app/models/side.rb
# == Schema Information
#
# Table name: sides
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  temp       :string(255)
#  time       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Side < ActiveRecord::Base
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  email           :string(255)
#  created_at      :datetime
#  updated_at      :datetime
#  password_digest :string(255)
#

class User < ActiveRecord::Base

  has_secure_password

  before_create :create_remember_token
  before_save { |user| user.email = email.downcase }

  validates :name, presence: true, length: {maximum: 50}
  validates :email, presence: true, uniqueness: {case_sensitive: false}
  validates :password, presence: true, length: {minimum: 6}
  validates :password_confirmation, presence: true

  private

  def create_remember_token
  	self.remember_token = SecureRandom.urlsafe_base64
  end

  before_save :create_remember_token

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  include SessionsHelper

  protect_from_forgery with: :exception

end

app/controllers/meats_controller.rb
class MeatsController < ApplicationController
  def show
  end

  def index
    #@meat = Meat.where(:name)
  end

  #def beef
    #@beef = Meat.where(:name => 'Beef')
  #end
end

app/controllers/pasta_rices_controller.rb
class PastaRicesController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  before_filter :signed_in_user, only: [:create, :new, :edit, :update]

  def index
  	@recipes = Recipe.all
  end

  def new
    @recipe = Recipe.new
  end

  def create
    recipe = Recipe.create(recipe_params)
    redirect_to(recipe)
  end

  def show
  	@recipe = Recipe.find(params[:id])
  end

  def edit
  	@recipe = Recipe.find(params[:id])
  end

  def update
  	recipe = Recipe.find(params[:id])
  	recipe.update_attributes(recipe_params)
  	redirect_to(recipe)
  end

  def destroy
    recipe = Recipe.find(params[:id])
    recipe.delete
    redirect_to(recipes_path)
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :temp, :cooktime, :ingredients, :instructions)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
  	signin_params = params[:session]
  	user=User.find_by_email(signin_params[:email].downcase)
  	if user && user.authenticate(signin_params[:password])
      sign_in user
  		redirect_to user
  	else
  		flash.now[:error]='Invalid email/password combination'
  		render :new
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
  def index
  end
end

app/controllers/sides_controller.rb
class SidesController < ApplicationController
  def show
  end

  def index
   # @side = Side.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new()
  end

  def show
  	@user = User.find(params[:id])
  end

  def create
  	new_user = params.require(:user).permit(:name, :email, :password, :password_confirmation)
  	@user=User.new(new_user)
  	if @user.save
  		flash[:success] = "Welcome to Sous Chef!"
  	    sign_in @user
  		redirect_to @user
    else
    	render 'new'
    end
  end
  
  def update
  	@user = User.find(params[:id])
  	@user.update_attributes(params[:user])
  	render :show
  end

  def destroy
  	sign_out
  	redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meats_helper.rb
module MeatsHelper
end

app/helpers/pasta_rices_helper.rb
module PastaRicesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def signed_in_user
    unless signed_in?
        session[:return_to] = request.url
        redirect_to signin_url, notice: "Please sign in."
    end
  end

  def sign_out
    @current_user = nil
    cookies.delete(:remember_token)
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end

end

app/helpers/sides_helper.rb
module SidesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><strong>Sous Chef</strong></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

  <!-- Below disables form submission on Enter -->
  <script type="text/javascript"> 

  function stopRKey(evt) { 
    var evt = (evt) ? evt : ((event) ? event : null); 
    var node = (evt.target) ? evt.target : ((evt.srcElement) ? evt.srcElement : null); 
  if ((evt.keyCode == 13) && (node.type=="text"))  {return false;} 
  } 

  document.onkeypress = stopRKey; 

  </script>

</head>

<body>

<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"><strong>Sous Chef</strong></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "My Profile", current_user %></li>
      <ul class="nav navbar-nav">
        
        <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Categories <b class="caret"></b></a>
          <ul class="dropdown-menu">
           	<li><%= link_to "Meats", meats_path %>
          	<li><%= link_to "Pasta/Rice", pasta_rices_path %></li>
          	<li><%= link_to "Sides", sides_path %></li>
            <li class="divider"></li>
            <li><%= link_to('Mom\'s Cookbook', recipes_path) %></li>
          </ul>
        </li>
    </div> 
  </div>
</nav> 
<div class="container">
<%= yield %>
</div>
</body>
</html>

app/views/meats/index.html.erb
<div class="btn-group btn-group-justified">
<div class="btn-group">
  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
    Beef <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" role="menu">
    <li><a href="#">Tenderloin</a></li>
    <li><a href="#">Roast</a></li>
    <li><a href="#">Brisket</a></li>
    <li><a href="#">Ribs</a></li>
    <li><a href="#">Steak</a></li>
    <li><a href="#">Tri-Tip</a></li>
  </ul>
</div>
<div class="btn-group">
  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
    Pork <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" role="menu">
    <li><a href="#">Tenderloin</a></li>
    <li><a href="#">Roast</a></li>
    <li><a href="#">Ribs</a></li>
    <li><a href="#">Ham</a></li>
    <li><a href="#">Chop</a></li>
  </ul>
</div>
<div class="btn-group">
  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
    Lamb <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" role="menu">
    <li><a href="#">Leg</a></li>
    <li><a href="#">Rack</a></li>
  </ul>
</div>
<div class="btn-group">
  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
    Chicken <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" role="menu">
    <li><a href="#">Whole</a></li>
    <li><a href="#">Breast(Bone-In)</a></li>
    <li><a href="#">Breast(Boneless)</a></li>
    <li><a href="#">Leg</a></li>
    <li><a href="#">Thigh</a></li>
  </ul>
</div>
<div class="btn-group">
  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
    Turkey <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" role="menu">
    <li><a href="#">Breast</a></li>
  </ul>
</div>
<div class="btn-group">
  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
    Fish <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" role="menu">
    <li><a href="#">Whole</a></li>
    <li><a href="#">Fillet</a></li>
  </ul>
</div>
</div>

app/views/meats/show.html.erb
<!-- response = Typhoeus.get("http://api.yummly.com/v1/api/recipes?_app_id:83795ef3&_app_key=555d7d815f7c59506f3931a1cbbc57df&q="#{}"") -->

<!-- response = Typhoeus.get("http://api.yummly.com/v1/api/recipes?_app_id=83795ef3&_app_key=555d7d815f7c59506f3931a1cbbc57df&q="#{}"") 
puts "Here are some recipe suggestions for the item you chose:" response.body 
  end  -->

app/views/pasta_rices/index.html.erb
<div class="btn-group">
  <a href="#"><button type="submit" class="btn btn-default">Pasta</button></a>
  <a href="#"><button type="submit" class="btn btn-default">Quinoa</button></a>
  <a href="#"><button type="submit" class="btn btn-default">Couscous</button></a>
</div>

  <div class="btn-group">
    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
      Rices
      <span class="caret"></span>
    </button>
    <ul class="dropdown-menu">
      <li><a href="#">White</a></li>
      <li><a href="#">Brown</a></li>
      <li><a href="#">Long</a></li>
      <li><a href="#">Wild</a></li>
    </ul>
  </div>


  <div class="btn-group">
    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
      Oats
      <span class="caret"></span>
    </button>
    <ul class="dropdown-menu">
      <li><a href="#">Rolled</a></li>
      <li><a href="#">Steel-Cut</a></li>
    </ul>
  </div>

app/views/pasta_rices/show.html.erb
<h1>PastaRices#show</h1>
<p>Find me in app/views/pasta_rices/show.html.erb</p>

app/views/recipes/_form.html.erb
<%= form_for @recipe do |f| %>
  <%= f.text_field :name, :autofocus => true %>
  <%= f.label :name %>
  <br>
  <%= f.text_field :temp %>
  <%= f.label :temp %>
  <br>
  <%= f.text_field :cooktime %>
  <%= f.label :cooktime %>
  <br>
  <%= f.text_field :ingredients %>
  <%= f.label :ingredients %>
  <br>
  <%= f.text_field :instructions %>
  <%= f.label :instructions %>
  <br>
  
  <%= f.submit  class: "btn btn-primary" %>
<% end %>

app/views/recipes/edit.html.erb
<h1>Edit Recipe</h1>
<%= render :partial => 'form' %>

app/views/recipes/index.html.erb
<ul class="nav nav-pills">
  <li>
    <%= link_to('Add A Recipe', new_recipe_path) %>
  </li>
</ul>


<% @recipes.each do |recipe| %>
  <div class="row">
     <div class="span3 offset1">
      <p class="lead"><%= link_to(recipe.name, recipe) %></p>
      <p><%= recipe.temp %></p>
      <p><%= recipe.cooktime %></p>
      <p><%= recipe.ingredients %></p>
      <p><%= recipe.instructions %></p>
    </div>
  </div>
<% end %>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>
<%= render :partial => 'form' %>

app/views/recipes/show.html.erb
<ul class="nav nav-pills">
  <li><%= link_to('New Recipe', new_recipe_path) %></li>
  <li><%= link_to('Edit Recipe', edit_recipe_path(@recipe)) %></li>
  <li><%= link_to('Delete Recipe', @recipe, :method => :delete, :confirm => 'Are you sure?') %></li>
  <div class='spacer'></div>
</ul>

<div class="row">
  <div class="span3 offset1">
    <p class="lead"><%= @recipe.name %></p>
    <p><%= @recipe.temp %></p>
    <p><%= @recipe.cooktime %></p>
    <p><%= @recipe.ingredients %></p>
    <p><%= @recipe.instructions %></p>
    <div class="span8">
    </div>
  </div>
</div>

app/views/sides/index.html.erb
<div class="btn-group">
  <a href=""><button type="button" class="btn btn-default">Baked Potato</button></a>
  <a href="#"><button type="button" class="btn btn-default">Boiled Egg</button></a>
  <a href="#"><button type="button" class="btn btn-default">Asparagus</button></a>
  <a href="#"><button type="button" class="btn btn-default">Broccoli</button></a>
  <a href="#"><button type="button" class="btn btn-default">Brussels Sprouts</button></a>
  <a href="#"><button type="button" class="btn btn-default">Carrots</button></a>
  <a href="#"><button type="button" class="btn btn-default">Cauliflower</button></a>
  <a href="#"><button type="button" class="btn btn-default">Green Beans</button></a>
  <a href="#"><button type="button" class="btn btn-default">Peas</button></a>
</div>

app/views/sides/show.html.erb
<h1>Sides#show</h1>
<p>Find me in app/views/sides/show.html.erb</p>

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row">
    <div class="span6 offset3">
        <%= form_for(@user) do |f| %>
            <% unless @user.errors.count == 0   %>
            <div class="alert alert-error">
                The form contains <%= pluralize(@user.errors.count, "error") %>.
            </div>
            <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li>* <%= msg %></li>
            <% end %>
            </ul>
            <% end %>

            <%= f.label :name %>
            <%= f.text_field :name %>
            <br>
            <%= f.label :email %>
            <%= f.text_field :email %>
            <br>
            <%= f.label :password %>
            <%= f.password_field :password %>
            <br>
            <%= f.label :password_confirmation, "Confirmation" %>
            <%= f.password_field :password_confirmation %>
            <br>
            <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
        <% end %>
    </div>
</div>

app/views/users/show.html.erb
<div class="row">
    <aside class="span4">
        <section>
            <h3><%= @user.name %></h3>
            <h3><%= @user.email %></h3>
        </section>
    </aside>
</div>